### PR TITLE
Swift 2 ready and cleanup in Response class

### PR DESCRIPTION
**Pull request by kevto**
Hey,

I found this repo a week ago and when I tried to use it in my project, it gave me many syntax errors and issues with Travis. I converted the project to Swift 2 (xcode 7)

As for the Response class, it had countless booleans stored which could easily be replaced with a single variable. For that, I had to create two enumerations and added some switch cases in the init() of Response.

All unit tests turned positive and were also changed because of the new way of Response HTTP status code validation.

Travis: https://travis-ci.org/kevto/SwiftClient/builds/81558121

### CODE REVIEW

**Comment by kevto** [comment]
The build fails only on the newest push which is weird because the only changes happend in the README.md file. Rerun the build on travis and it will succeed. That's what I did to get the last push working on travis.

Still trying to figure out why the build is failing, the first time it's running.

**Comment by SandroMachado** [comment]
Looks like the travis is failing because `Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.`

Try to update the travis file to: - xcodebuild clean build test -project SwiftClient.xcodeproj -scheme SwiftClient `CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO`

**Comment by kevto** [comment]
Yeah, tried to use Adam's travis file. I've done what you told and it gives me yet another error about using an incorrect device. I'm going try something else once more before I commit more changes to this pull request, I'll take this matter to a clean project and see if I can reproduce the same error

**Comment by kevto** [comment]
Alright, it seems when I add the -sdk flag to the CLI command, the build will be successful.

**Comment by theadam** [comment]
I like this.  What do you think about updating the podspec version to 2.0.0 with this, and I can make it a release?  Also, would you mind squashing your commits?

**Comment by kevto** [comment]
Yeah, no problem. I will do that first thing tomorrow.

**Pull request closed without merging**
