### PR TITLE
Update Carthage configuration

### PR DESCRIPTION
**Pull request by diogoguimaraes**
This pull request updates the release enable testability flag so that Carthage builds won't fail.
I've also updated the version on the podspec file to 2.0.1 as it was not updated in master.

### CODE REVIEW

**Comment by theadam** [comment]
Hey, I actually just forgot to push master after pushing the tag.  My commit that is in the tag updating the podspec is now pushed. If you could remove your change to the podspec, This is acceptable!

**Comment by diogoguimaraes** [comment]
@theadam done.
Thank you!

**Comment by diogoguimaraes** [comment]
Hello @theadam 
Any ETA to a release including this fix?
Thanks.

**Comment by theadam** [comment]
just released to 2.0.2 for you!

**Pull request merged**
