### PR TITLE
Fix body encoding

### PR DESCRIPTION
**Pull request by SandroMachado**
This PR fixes the encoding for the response body.

### CODE REVIEW

**Comment by SandroMachado** [comment]
@theadam can you please make a release with this latest changes? 

Regards

**Comment by theadam** [comment]
@SandroMachado Would you be interested in being made into a maintainer, so you could accept PRs and create releases?  I no longer keep my iOS dev environment up to date.

**Comment by SandroMachado** [comment]
Sure! Thanks for the invite!

**Comment by theadam** [comment]
Just added you on Github, do you have a cocoapods email, I can add you as an owner there too.  Let me know if you need anything else

**Comment by SandroMachado** [comment]
@theadam looks like it is not working. I am getting this message publishing the new version on cocoa pods:
```
[!] You (sandroemachado@gmail.com) are not allowed to push new versions for this pod. The owners of this pod are theadam4257@gmail.com.
```

**Comment by theadam** [comment]
try now!

**Comment by SandroMachado** [comment]
Works! Thanks :)

**Pull request merged**
