### PR TITLE
Add podspec

### PR DESCRIPTION
**Pull request by nunofgs**
Thanks for the great library. I found it very enjoyable to use!

If you find this podspec acceptable, can you [submit](https://guides.cocoapods.org/making/making-a-cocoapod.html#release) it to Cocoapods?

### CODE REVIEW

**Comment by theadam** [comment]
Great idea!  Once we work out PR #3 I'll integrate cocoapods!

**Comment by theadam** [comment]
Do you have any experience with Swift and cocoapods?  I'm having trouble getting this published.  If youd like to see what im seeing, checkout master and run 'pod lib lint'

if you dont have any ideas, ill open an issue and continue to look for a solution.  Hopefully we can get it up on cocoapods!

**Comment by nunofgs** [comment]
I've published a couple of Objective-C pods but I haven't published a Swift pod yet.

Linting the pod seems to work for me:

```bash
❯ pod lib lint

 -> SwiftClient (1.0.0)

SwiftClient passed validation.
```

Can you paste your output?

**Comment by theadam** [comment]
Wow, you are right! It turns out I had a couple of different versions of cocoapods installed. Linting worked great with the latest.  Thanks for checking that out.

**Comment by theadam** [comment]
Thanks for all your help!  Swiftclient v1 is up on cocoapods now!

**Comment by nunofgs** [comment]
Awesome! Thanks for all your work.

**Pull request merged**
