### PR TITLE
Fix compiler errors

### PR DESCRIPTION
**Pull request by nunofgs**

### CODE REVIEW

**Comment by theadam** [comment]
Hey man, thanks for the pull request.  When i build, i get compiler errors in the Test file.  Anyway you can include that fix in the Pull request?  Do you think we should also go ahead and update the project format to xcode 6.3 compatibility?  

Once these things are changed, ill accept your other pull request and publish to cocoapods!  Thanks!

**Comment by nunofgs** [comment]
Hi Adam,

Right you are. I've updated the PR. I didn't realize you had tests. Very nice :)

Since you have tests, how about setting up Travis on this repo?

**Comment by theadam** [comment]
Thats a great idea.  I have never used Travis CI but ill look into it!  

Thanks for updating those tests!  I'm merging now, and ill look at #4.

**Comment by theadam** [comment]
Added a Travis build, but its incompatible with the new version of swift.  Its ready to go whenever Travis CI updates!  Thanks for the suggestions!

**Pull request merged**
